# اسم سير العمل
name: Run Python Bot Experiment

# التشغيل يدوياً فقط
on:
  workflow_dispatch:

jobs:
  run-bot:
    # سيتم التشغيل على نظام أوبنتو
    runs-on: ubuntu-latest

    steps:
      # 1. جلب الكود من المستودع
      - name: Check out repository code
        uses: actions/checkout@v4

      # 2. إعداد بيئة بايثون
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. تثبيت برنامج FFmpeg
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      # 4. تثبيت مكتبات بايثون وتحديث yt-dlp
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade yt-dlp

      # 5. تشغيل البوت مباشرة
      - name: Run the Python bot
        run: python bot.py
